name: Ultra TV - Generar APK

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      # 1. Descargar el repositorio
      - name: Descargar repositorio
        uses: actions/checkout@v4

      # 2. Instalar Java 17
      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # 3. Instalar Gradle
      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.13'

      # 4. Instalar Android SDK
      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      # 5. Instalar SDK necesario
      - name: Instalar Android SDK 36
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-36"
          sdkmanager "build-tools;36.0.0"

      # 6. Buscar el ZIP
      - name: Comprobar ZIP
        run: |
          echo "Archivos del repositorio:"
          ls -lah

      # 7. Descomprimir Ultra TV
      - name: Descomprimir proyecto Ultra TV
        run: |
          mkdir -p ultratv
          unzip -o UltraTV-GitHub-logo.zip -d ultratv

          echo "Proyecto descomprimido:"
          find ultratv -maxdepth 3 -type f | sort

      # 8. Comprobar estructura
      - name: Comprobar proyecto Android
        run: |
          test -f ultratv/settings.gradle.kts
          test -f ultratv/build.gradle.kts
          test -f ultratv/app/build.gradle.kts
          echo "Proyecto Android encontrado correctamente."

      # 9. Compilar APK Debug
      - name: Generar APK
        working-directory: ultratv
        run: |
          gradle :app:assembleDebug --no-daemon

      # 10. Guardar APK
      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: UltraTV-APK
          path: ultratv/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
